from __future__ import annotations

import dataclasses
import json
from pathlib import Path

from search_rsi.meta.archive import ArchiveEntry
from search_rsi.meta.config import HarnessConfig

_SERVE_TEMPLATE = '''"""Generated by search_rsi.meta.export — do not hand-edit.

Loads the config this meta-loop selected as the best-scoring, lowest-latency
option for the benchmarked search problem, and exposes it as a plain function a
production server can call. Regenerate by re-running the meta-loop and exporting
again rather than editing this file directly.
"""
from __future__ import annotations

import json
from pathlib import Path

from search_rsi.harness import Harness
from search_rsi.types import Document

CONFIG_PATH = Path(__file__).with_name("config.json")


def load_harness(documents: list[Document]) -> Harness:
    config = json.loads(CONFIG_PATH.read_text())
    return Harness.local(documents=documents, **config)


def answer(harness: Harness, question: str, tool_budget: int = 4):
    from search_rsi.types import Task

    task = Task(question=question, gold_doc_ids=[], gold_answer="", tool_budget=tool_budget)
    result = harness.run(task, memory_enabled=False, is_training_task=False)
    return result.answer, result.citations
'''


def export_variant(entry: ArchiveEntry, out_dir: Path) -> Path:
    """Writes a deployable artifact for one archive entry: `config.json` (the exact
    HarnessConfig, minus meta-loop-only bookkeeping) plus a `serve.py` that builds a
    Harness from it and exposes a plain `answer()` call — the actual deliverable for
    "describe a search problem, get the best-scoring lowest-latency config that goes
    on a production server," not just a benchmark table.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    config_dict = dataclasses.asdict(entry.config)
    (out_dir / "config.json").write_text(json.dumps(config_dict, indent=2) + "\n")
    (out_dir / "serve.py").write_text(_SERVE_TEMPLATE)
    manifest = {
        "config_label": entry.config.label(),
        "mean_score": entry.score.mean_score,
        "mean_tool_calls": entry.score.mean_tool_calls,
        "mean_latency_ms": entry.score.mean_latency_ms,
        "n_eval_tasks": entry.score.n_tasks,
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return out_dir
