from __future__ import annotations

import json
from pathlib import Path

from search_rsi.memory.rewrites import RewriteRules
from search_rsi.pipeline import PipelineConfig
from search_rsi.rsi.evaluate import PipelineScore

_SERVE_TEMPLATE = '''"""Generated by search_rsi.rsi.export — do not hand-edit; re-run the optimizer.

Loads the pipeline the optimizer selected (config.json) and the query-rewrite rules
it learned (rewrites.json), and exposes plain functions a production service can
call. Usage from the command line:

    python serve.py corpus.jsonl "red sneakers under $80"

where corpus.jsonl has one {"_id", "title", "text", "metadata"} object per line.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from search_rsi.memory import RewriteRules
from search_rsi.pipeline import PipelineConfig, SearchPipeline
from search_rsi.types import Document

HERE = Path(__file__).resolve().parent


def load_pipeline(documents: list[Document]) -> SearchPipeline:
    config = PipelineConfig.from_dict(json.loads((HERE / "config.json").read_text()))
    rules = RewriteRules.from_json(json.loads((HERE / "rewrites.json").read_text()))
    return SearchPipeline(documents, config, rules)


def search(pipeline: SearchPipeline, query: str, top_k: int = 10) -> list[tuple[str, float]]:
    return pipeline.search(query, top_k).hits


def load_jsonl(path: str) -> list[Document]:
    with open(path) as fh:
        rows = [json.loads(line) for line in fh if line.strip()]
    return [Document(doc_id=str(r["_id"]), title=r.get("title", ""), text=r.get("text", ""),
                     metadata=r.get("metadata") or {}) for r in rows]


if __name__ == "__main__":
    pipeline = load_pipeline(load_jsonl(sys.argv[1]))
    for doc_id, score in search(pipeline, " ".join(sys.argv[2:])):
        print(f"{score:8.4f}  {doc_id}")
'''


def export_pipeline(
    out_dir: Path,
    problem_name: str,
    config: PipelineConfig,
    rules: RewriteRules | None,
    held_out: PipelineScore,
    meta_val: PipelineScore | None = None,
) -> Path:
    """Write a deployable artifact: config.json + rewrites.json + manifest.json +
    serve.py. The manifest records held-out numbers — the only ones a deploy
    decision may rest on (docs/META_RSI.md, Guardrail 2)."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "config.json").write_text(json.dumps(config.to_dict(), indent=2) + "\n")
    rules_json = (rules or RewriteRules()).to_json() if config.use_learned_rewrites else []
    (out_dir / "rewrites.json").write_text(json.dumps(rules_json, indent=2) + "\n")
    (out_dir / "serve.py").write_text(_SERVE_TEMPLATE)
    manifest = {
        "problem": problem_name,
        "config_label": config.label(),
        "held_out": {"primary": held_out.mean_score, **held_out.metrics,
                     "latency_ms": held_out.mean_latency_ms, "n_queries": held_out.n_tasks},
        "meta_val_primary": meta_val.mean_score if meta_val else None,
        "n_rewrite_rules": len(rules_json),
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return out_dir
